#debug: true
spring:
  banner:
    location: classpath:myBanner.txt
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "someGroup"
    producer:
      bootstrap-servers: "localhost:9092"
util:
  about:
    author: htG
    info: Educational application
    version: 1.0
  random-int: "${random.int}"
  random-uuid: "${random.uuid}"
  test: one